// @generated by chaos-tproxy-codegen.
// Do NOT edit by hand. Re-run
//   (cd tools/codegen && cargo run --release)
// after editing schemas/chaos-tproxy.openapi.yaml.
//
// Only the `types` module from progenitor's output is kept;
// the (empty) HTTP Client wrapper is intentionally dropped
// so chaos-tproxy-proxy doesn't depend on reqwest /
// progenitor_client.

#![allow(clippy::all, missing_docs, unused_imports)]

/// Error types.
pub mod error {
    /// Error from a `TryFrom` or `FromStr` implementation.
    pub struct ConversionError(::std::borrow::Cow<'static, str>);
    impl ::std::error::Error for ConversionError {}
    impl ::std::fmt::Display for ConversionError {
        fn fmt(
            &self,
            f: &mut ::std::fmt::Formatter<'_>,
        ) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }
    impl ::std::fmt::Debug for ConversionError {
        fn fmt(
            &self,
            f: &mut ::std::fmt::Formatter<'_>,
        ) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }
    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }
    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}
///`Actions`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "properties": {
///    "abort": {
///      "description": "If true, terminate the request/response with a 502.",
///      "type": [
///        "boolean",
///        "null"
///      ]
///    },
///    "delay": {
///      "description": "Wait this long before continuing. Format is the `humantime`\ncrate's flavor: `\"100ms\"`, `\"3s\"`, `\"1m30s\"`, etc.\n",
///      "type": [
///        "string",
///        "null"
///      ]
///    },
///    "patch": {
///      "oneOf": [
///        {
///          "type": "null"
///        },
///        {
///          "allOf": [
///            {
///              "$ref": "#/components/schemas/PatchAction"
///            }
///          ]
///        }
///      ]
///    },
///    "replace": {
///      "oneOf": [
///        {
///          "type": "null"
///        },
///        {
///          "allOf": [
///            {
///              "$ref": "#/components/schemas/ReplaceAction"
///            }
///          ]
///        }
///      ]
///    }
///  }
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct Actions {
    ///If true, terminate the request/response with a 502.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub abort: ::std::option::Option<bool>,
    /**Wait this long before continuing. Format is the `humantime`
crate's flavor: `"100ms"`, `"3s"`, `"1m30s"`, etc.
*/
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub delay: ::std::option::Option<::std::string::String>,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub patch: ::std::option::Option<PatchAction>,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub replace: ::std::option::Option<ReplaceAction>,
}
impl ::std::convert::From<&Actions> for Actions {
    fn from(value: &Actions) -> Self {
        value.clone()
    }
}
impl ::std::default::Default for Actions {
    fn default() -> Self {
        Self {
            abort: Default::default(),
            delay: Default::default(),
            patch: Default::default(),
            replace: Default::default(),
        }
    }
}
///Top-level config the proxy reads at startup.
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "Top-level config the proxy reads at startup.",
///  "type": "object",
///  "required": [
///    "listen_port"
///  ],
///  "properties": {
///    "listen_port": {
///      "description": "TCP port the proxy listens on (with `IP_TRANSPARENT`).\nBPF / iptables datapath redirects original-dst traffic to\nthis port.\n",
///      "type": "integer",
///      "format": "int32",
///      "maximum": 65535.0,
///      "minimum": 1.0
///    },
///    "proxy_mark": {
///      "description": "`SO_MARK` set on upstream sockets opened by the proxy.\nUsed by the eBPF egress program to skip the proxy's own\nforward traffic and avoid redirect loops.\n",
///      "type": [
///        "integer",
///        "null"
///      ],
///      "format": "int64",
///      "maximum": 4294967295.0,
///      "minimum": 0.0
///    },
///    "role": {
///      "description": "If set, rules only fire when the connection's\n(src_ip, dst_ip) matches the configured side.\n",
///      "oneOf": [
///        {
///          "type": "null"
///        },
///        {
///          "allOf": [
///            {
///              "$ref": "#/components/schemas/Role"
///            }
///          ]
///        }
///      ]
///    },
///    "rules": {
///      "description": "Chaos rules, evaluated in declaration order.",
///      "default": [],
///      "type": "array",
///      "items": {
///        "$ref": "#/components/schemas/Rule"
///      }
///    }
///  }
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct ChaosTproxyConfig {
    /**TCP port the proxy listens on (with `IP_TRANSPARENT`).
BPF / iptables datapath redirects original-dst traffic to
this port.
*/
    pub listen_port: ::std::num::NonZeroU32,
    /**`SO_MARK` set on upstream sockets opened by the proxy.
Used by the eBPF egress program to skip the proxy's own
forward traffic and avoid redirect loops.
*/
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub proxy_mark: ::std::option::Option<i64>,
    /**If set, rules only fire when the connection's
(src_ip, dst_ip) matches the configured side.
*/
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub role: ::std::option::Option<Role>,
    ///Chaos rules, evaluated in declaration order.
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub rules: ::std::vec::Vec<Rule>,
}
impl ::std::convert::From<&ChaosTproxyConfig> for ChaosTproxyConfig {
    fn from(value: &ChaosTproxyConfig) -> Self {
        value.clone()
    }
}
///`PatchAction`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "properties": {
///    "body": {
///      "oneOf": [
///        {
///          "type": "null"
///        },
///        {
///          "allOf": [
///            {
///              "$ref": "#/components/schemas/PatchBody"
///            }
///          ]
///        }
///      ]
///    },
///    "headers": {
///      "description": "Headers to append. Each entry is a `[name, value]` pair;\nduplicate names are allowed for headers like Cookie.\n",
///      "type": [
///        "array",
///        "null"
///      ],
///      "items": {
///        "type": "array",
///        "items": {
///          "type": "string"
///        },
///        "maxItems": 2,
///        "minItems": 2
///      }
///    },
///    "queries": {
///      "description": "Query parameters to append. Each entry is a `[key, value]`\npair; duplicate keys are intentionally allowed (e.g.\n`foo=1&foo=2`), which is why this is an array of pairs\nrather than a map.\n",
///      "type": [
///        "array",
///        "null"
///      ],
///      "items": {
///        "type": "array",
///        "items": {
///          "type": "string"
///        },
///        "maxItems": 2,
///        "minItems": 2
///      }
///    }
///  }
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct PatchAction {
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub body: ::std::option::Option<PatchBody>,
    /**Headers to append. Each entry is a `[name, value]` pair;
duplicate names are allowed for headers like Cookie.
*/
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub headers: ::std::option::Option<::std::vec::Vec<[::std::string::String; 2usize]>>,
    /**Query parameters to append. Each entry is a `[key, value]`
pair; duplicate keys are intentionally allowed (e.g.
`foo=1&foo=2`), which is why this is an array of pairs
rather than a map.
*/
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub queries: ::std::option::Option<::std::vec::Vec<[::std::string::String; 2usize]>>,
}
impl ::std::convert::From<&PatchAction> for PatchAction {
    fn from(value: &PatchAction) -> Self {
        value.clone()
    }
}
impl ::std::default::Default for PatchAction {
    fn default() -> Self {
        Self {
            body: Default::default(),
            headers: Default::default(),
            queries: Default::default(),
        }
    }
}
///`PatchBody`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "required": [
///    "contents"
///  ],
///  "properties": {
///    "contents": {
///      "$ref": "#/components/schemas/PatchBodyContents"
///    }
///  }
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct PatchBody {
    pub contents: PatchBodyContents,
}
impl ::std::convert::From<&PatchBody> for PatchBody {
    fn from(value: &PatchBody) -> Self {
        value.clone()
    }
}
///`PatchBodyContents`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "oneOf": [
///    {
///      "$ref": "#/components/schemas/PatchBodyContentsJson"
///    }
///  ]
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(transparent)]
pub struct PatchBodyContents(pub PatchBodyContentsJson);
impl ::std::ops::Deref for PatchBodyContents {
    type Target = PatchBodyContentsJson;
    fn deref(&self) -> &PatchBodyContentsJson {
        &self.0
    }
}
impl ::std::convert::From<PatchBodyContents> for PatchBodyContentsJson {
    fn from(value: PatchBodyContents) -> Self {
        value.0
    }
}
impl ::std::convert::From<&PatchBodyContents> for PatchBodyContents {
    fn from(value: &PatchBodyContents) -> Self {
        value.clone()
    }
}
impl ::std::convert::From<PatchBodyContentsJson> for PatchBodyContents {
    fn from(value: PatchBodyContentsJson) -> Self {
        Self(value)
    }
}
///`PatchBodyContentsJson`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "required": [
///    "type",
///    "value"
///  ],
///  "properties": {
///    "type": {
///      "type": "string",
///      "enum": [
///        "JSON"
///      ]
///    },
///    "value": {
///      "description": "JSON value (as a string). The proxy parses this and merges\nit into the request/response body using RFC 7396 JSON\nMerge Patch semantics.\n",
///      "type": "string"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct PatchBodyContentsJson {
    #[serde(rename = "type")]
    pub type_: PatchBodyContentsJsonType,
    /**JSON value (as a string). The proxy parses this and merges
it into the request/response body using RFC 7396 JSON
Merge Patch semantics.
*/
    pub value: ::std::string::String,
}
impl ::std::convert::From<&PatchBodyContentsJson> for PatchBodyContentsJson {
    fn from(value: &PatchBodyContentsJson) -> Self {
        value.clone()
    }
}
///`PatchBodyContentsJsonType`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "string",
///  "enum": [
///    "JSON"
///  ]
///}
/// ```
/// </details>
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd
)]
pub enum PatchBodyContentsJsonType {
    #[serde(rename = "JSON")]
    Json,
}
impl ::std::convert::From<&Self> for PatchBodyContentsJsonType {
    fn from(value: &PatchBodyContentsJsonType) -> Self {
        value.clone()
    }
}
impl ::std::fmt::Display for PatchBodyContentsJsonType {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Json => f.write_str("JSON"),
        }
    }
}
impl ::std::str::FromStr for PatchBodyContentsJsonType {
    type Err = self::error::ConversionError;
    fn from_str(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "JSON" => Ok(Self::Json),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for PatchBodyContentsJsonType {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for PatchBodyContentsJsonType {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for PatchBodyContentsJsonType {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
///`ReplaceAction`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "properties": {
///    "body": {
///      "oneOf": [
///        {
///          "type": "null"
///        },
///        {
///          "allOf": [
///            {
///              "$ref": "#/components/schemas/ReplaceBody"
///            }
///          ]
///        }
///      ]
///    },
///    "code": {
///      "description": "Replace response status code. Ignored on Request rules.",
///      "type": [
///        "integer",
///        "null"
///      ],
///      "format": "int32",
///      "maximum": 599.0,
///      "minimum": 100.0
///    },
///    "headers": {
///      "description": "Replace (set) request/response header values.",
///      "type": [
///        "object",
///        "null"
///      ],
///      "additionalProperties": {
///        "type": "string"
///      }
///    },
///    "method": {
///      "description": "Replace request method. Ignored on Response rules.",
///      "type": [
///        "string",
///        "null"
///      ]
///    },
///    "path": {
///      "description": "Replace request path. Ignored on Response rules.",
///      "type": [
///        "string",
///        "null"
///      ]
///    },
///    "queries": {
///      "description": "Replace request query parameters with this map. Ignored on Response rules.",
///      "type": [
///        "object",
///        "null"
///      ],
///      "additionalProperties": {
///        "type": "string"
///      }
///    }
///  }
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct ReplaceAction {
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub body: ::std::option::Option<ReplaceBody>,
    ///Replace response status code. Ignored on Request rules.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub code: ::std::option::Option<i32>,
    ///Replace (set) request/response header values.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub headers: ::std::option::Option<
        ::std::collections::HashMap<::std::string::String, ::std::string::String>,
    >,
    ///Replace request method. Ignored on Response rules.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub method: ::std::option::Option<::std::string::String>,
    ///Replace request path. Ignored on Response rules.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub path: ::std::option::Option<::std::string::String>,
    ///Replace request query parameters with this map. Ignored on Response rules.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub queries: ::std::option::Option<
        ::std::collections::HashMap<::std::string::String, ::std::string::String>,
    >,
}
impl ::std::convert::From<&ReplaceAction> for ReplaceAction {
    fn from(value: &ReplaceAction) -> Self {
        value.clone()
    }
}
impl ::std::default::Default for ReplaceAction {
    fn default() -> Self {
        Self {
            body: Default::default(),
            code: Default::default(),
            headers: Default::default(),
            method: Default::default(),
            path: Default::default(),
            queries: Default::default(),
        }
    }
}
///`ReplaceBody`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "required": [
///    "contents"
///  ],
///  "properties": {
///    "contents": {
///      "$ref": "#/components/schemas/ReplaceBodyContents"
///    }
///  }
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct ReplaceBody {
    pub contents: ReplaceBodyContents,
}
impl ::std::convert::From<&ReplaceBody> for ReplaceBody {
    fn from(value: &ReplaceBody) -> Self {
        value.clone()
    }
}
///`ReplaceBodyContents`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "oneOf": [
///    {
///      "$ref": "#/components/schemas/ReplaceBodyContentsText"
///    },
///    {
///      "$ref": "#/components/schemas/ReplaceBodyContentsBase64"
///    }
///  ]
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(untagged)]
pub enum ReplaceBodyContents {
    Text(ReplaceBodyContentsText),
    Base64(ReplaceBodyContentsBase64),
}
impl ::std::convert::From<&Self> for ReplaceBodyContents {
    fn from(value: &ReplaceBodyContents) -> Self {
        value.clone()
    }
}
impl ::std::convert::From<ReplaceBodyContentsText> for ReplaceBodyContents {
    fn from(value: ReplaceBodyContentsText) -> Self {
        Self::Text(value)
    }
}
impl ::std::convert::From<ReplaceBodyContentsBase64> for ReplaceBodyContents {
    fn from(value: ReplaceBodyContentsBase64) -> Self {
        Self::Base64(value)
    }
}
///`ReplaceBodyContentsBase64`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "required": [
///    "type",
///    "value"
///  ],
///  "properties": {
///    "type": {
///      "type": "string",
///      "enum": [
///        "BASE64"
///      ]
///    },
///    "value": {
///      "description": "Base64-encoded replacement body (decoded by the proxy at apply time).",
///      "type": "string"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct ReplaceBodyContentsBase64 {
    #[serde(rename = "type")]
    pub type_: ReplaceBodyContentsBase64Type,
    ///Base64-encoded replacement body (decoded by the proxy at apply time).
    pub value: ::std::string::String,
}
impl ::std::convert::From<&ReplaceBodyContentsBase64> for ReplaceBodyContentsBase64 {
    fn from(value: &ReplaceBodyContentsBase64) -> Self {
        value.clone()
    }
}
///`ReplaceBodyContentsBase64Type`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "string",
///  "enum": [
///    "BASE64"
///  ]
///}
/// ```
/// </details>
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd
)]
pub enum ReplaceBodyContentsBase64Type {
    #[serde(rename = "BASE64")]
    Base64,
}
impl ::std::convert::From<&Self> for ReplaceBodyContentsBase64Type {
    fn from(value: &ReplaceBodyContentsBase64Type) -> Self {
        value.clone()
    }
}
impl ::std::fmt::Display for ReplaceBodyContentsBase64Type {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Base64 => f.write_str("BASE64"),
        }
    }
}
impl ::std::str::FromStr for ReplaceBodyContentsBase64Type {
    type Err = self::error::ConversionError;
    fn from_str(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "BASE64" => Ok(Self::Base64),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for ReplaceBodyContentsBase64Type {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for ReplaceBodyContentsBase64Type {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for ReplaceBodyContentsBase64Type {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
///`ReplaceBodyContentsText`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "required": [
///    "type",
///    "value"
///  ],
///  "properties": {
///    "type": {
///      "type": "string",
///      "enum": [
///        "TEXT"
///      ]
///    },
///    "value": {
///      "description": "Literal replacement body.",
///      "type": "string"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct ReplaceBodyContentsText {
    #[serde(rename = "type")]
    pub type_: ReplaceBodyContentsTextType,
    ///Literal replacement body.
    pub value: ::std::string::String,
}
impl ::std::convert::From<&ReplaceBodyContentsText> for ReplaceBodyContentsText {
    fn from(value: &ReplaceBodyContentsText) -> Self {
        value.clone()
    }
}
///`ReplaceBodyContentsTextType`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "string",
///  "enum": [
///    "TEXT"
///  ]
///}
/// ```
/// </details>
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd
)]
pub enum ReplaceBodyContentsTextType {
    #[serde(rename = "TEXT")]
    Text,
}
impl ::std::convert::From<&Self> for ReplaceBodyContentsTextType {
    fn from(value: &ReplaceBodyContentsTextType) -> Self {
        value.clone()
    }
}
impl ::std::fmt::Display for ReplaceBodyContentsTextType {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Text => f.write_str("TEXT"),
        }
    }
}
impl ::std::str::FromStr for ReplaceBodyContentsTextType {
    type Err = self::error::ConversionError;
    fn from_str(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "TEXT" => Ok(Self::Text),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for ReplaceBodyContentsTextType {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for ReplaceBodyContentsTextType {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for ReplaceBodyContentsTextType {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
///`Role`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "oneOf": [
///    {
///      "$ref": "#/components/schemas/RoleClient"
///    },
///    {
///      "$ref": "#/components/schemas/RoleServer"
///    }
///  ]
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(untagged)]
pub enum Role {
    Client(RoleClient),
    Server(RoleServer),
}
impl ::std::convert::From<&Self> for Role {
    fn from(value: &Role) -> Self {
        value.clone()
    }
}
impl ::std::convert::From<RoleClient> for Role {
    fn from(value: RoleClient) -> Self {
        Self::Client(value)
    }
}
impl ::std::convert::From<RoleServer> for Role {
    fn from(value: RoleServer) -> Self {
        Self::Server(value)
    }
}
///`RoleClient`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "required": [
///    "Client"
///  ],
///  "properties": {
///    "Client": {
///      "description": "Rule fires when the connection's source ip is in this list.",
///      "type": "array",
///      "items": {
///        "type": "string",
///        "format": "ipv4"
///      }
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct RoleClient {
    ///Rule fires when the connection's source ip is in this list.
    #[serde(rename = "Client")]
    pub client: ::std::vec::Vec<::std::net::Ipv4Addr>,
}
impl ::std::convert::From<&RoleClient> for RoleClient {
    fn from(value: &RoleClient) -> Self {
        value.clone()
    }
}
///`RoleServer`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "required": [
///    "Server"
///  ],
///  "properties": {
///    "Server": {
///      "description": "Rule fires when the connection's destination ip is in this list.",
///      "type": "array",
///      "items": {
///        "type": "string",
///        "format": "ipv4"
///      }
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct RoleServer {
    ///Rule fires when the connection's destination ip is in this list.
    #[serde(rename = "Server")]
    pub server: ::std::vec::Vec<::std::net::Ipv4Addr>,
}
impl ::std::convert::From<&RoleServer> for RoleServer {
    fn from(value: &RoleServer) -> Self {
        value.clone()
    }
}
///`Rule`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "required": [
///    "actions",
///    "selector",
///    "target"
///  ],
///  "properties": {
///    "actions": {
///      "$ref": "#/components/schemas/Actions"
///    },
///    "selector": {
///      "$ref": "#/components/schemas/Selector"
///    },
///    "target": {
///      "$ref": "#/components/schemas/Target"
///    }
///  }
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct Rule {
    pub actions: Actions,
    pub selector: Selector,
    pub target: Target,
}
impl ::std::convert::From<&Rule> for Rule {
    fn from(value: &Rule) -> Self {
        value.clone()
    }
}
///`Selector`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "properties": {
///    "code": {
///      "description": "Match only when the response status equals this. Ignored on Request rules.",
///      "type": [
///        "integer",
///        "null"
///      ],
///      "format": "int32",
///      "maximum": 599.0,
///      "minimum": 100.0
///    },
///    "method": {
///      "description": "HTTP method (GET / POST / …).",
///      "type": [
///        "string",
///        "null"
///      ]
///    },
///    "path": {
///      "description": "Wildcard glob against the request URI path. Syntax is the\n`wildmatch` crate's flavor: `?` matches one char, `*`\nmatches zero-or-more chars. Case-sensitive.\n",
///      "type": [
///        "string",
///        "null"
///      ]
///    },
///    "port": {
///      "description": "Match only when the original-dst port equals this.",
///      "type": [
///        "integer",
///        "null"
///      ],
///      "format": "int32",
///      "maximum": 65535.0,
///      "minimum": 1.0
///    },
///    "request_headers": {
///      "description": "Match only when every (name, value) pair appears in the request headers.",
///      "type": [
///        "object",
///        "null"
///      ],
///      "additionalProperties": {
///        "type": "string"
///      }
///    },
///    "response_headers": {
///      "description": "Match only when every (name, value) pair appears in the response headers. Ignored on Request rules.",
///      "type": [
///        "object",
///        "null"
///      ],
///      "additionalProperties": {
///        "type": "string"
///      }
///    }
///  }
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct Selector {
    ///Match only when the response status equals this. Ignored on Request rules.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub code: ::std::option::Option<i32>,
    ///HTTP method (GET / POST / …).
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub method: ::std::option::Option<::std::string::String>,
    /**Wildcard glob against the request URI path. Syntax is the
`wildmatch` crate's flavor: `?` matches one char, `*`
matches zero-or-more chars. Case-sensitive.
*/
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub path: ::std::option::Option<::std::string::String>,
    ///Match only when the original-dst port equals this.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub port: ::std::option::Option<::std::num::NonZeroU32>,
    ///Match only when every (name, value) pair appears in the request headers.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub request_headers: ::std::option::Option<
        ::std::collections::HashMap<::std::string::String, ::std::string::String>,
    >,
    ///Match only when every (name, value) pair appears in the response headers. Ignored on Request rules.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub response_headers: ::std::option::Option<
        ::std::collections::HashMap<::std::string::String, ::std::string::String>,
    >,
}
impl ::std::convert::From<&Selector> for Selector {
    fn from(value: &Selector) -> Self {
        value.clone()
    }
}
impl ::std::default::Default for Selector {
    fn default() -> Self {
        Self {
            code: Default::default(),
            method: Default::default(),
            path: Default::default(),
            port: Default::default(),
            request_headers: Default::default(),
            response_headers: Default::default(),
        }
    }
}
///Whether this rule matches against the HTTP request or the response.
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "Whether this rule matches against the HTTP request or the response.",
///  "type": "string",
///  "enum": [
///    "Request",
///    "Response"
///  ]
///}
/// ```
/// </details>
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd
)]
pub enum Target {
    Request,
    Response,
}
impl ::std::convert::From<&Self> for Target {
    fn from(value: &Target) -> Self {
        value.clone()
    }
}
impl ::std::fmt::Display for Target {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Request => f.write_str("Request"),
            Self::Response => f.write_str("Response"),
        }
    }
}
impl ::std::str::FromStr for Target {
    type Err = self::error::ConversionError;
    fn from_str(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "Request" => Ok(Self::Request),
            "Response" => Ok(Self::Response),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for Target {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for Target {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for Target {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
