[package]
name = "rs-tproxy"
version = "0.1.0"
authors = ["Andrewmatilde <davis6813585853062@outlook.com>"]
edition = "2018"

[[bin]]
name = "rs-tproxy"

[workspace]
members = [
    "parser",
    "proxy",
]
