[package]
name = "gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
[dependencies]
chaos-tproxy-controller = {path = "../../chaos-tproxy-controller"}
chaos-tproxy-proxy = {path = "../../chaos-tproxy-proxy"}
serde = {version = "1.0", features = ["derive"]}
serde_derive = "1.0.123"
serde_json = "1.0"
serde_urlencoded = "0.7"
serde_yaml = "0.8"
toml = "0.5.9"
