//! Regenerates chaos-tproxy's Rust schema types from the canonical
//! OpenAPI spec at `schemas/chaos-tproxy.openapi.yaml`.
//!
//! Run: `cargo run --release` from this directory.
//!
//! We only want type definitions — the OpenAPI spec has `paths: {}`
//! so the generated `Client` and `prelude` are dead weight that would
//! force `reqwest` + `progenitor_client` onto chaos-tproxy-proxy.
//! After codegen we walk the AST and keep only `pub mod types`,
//! re-emitted flattened (its contents become the file body).

use std::path::PathBuf;

use anyhow::{Context, Result};
use syn::{Item, ItemMod};

fn main() -> Result<()> {
    let repo_root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..");
    let spec_path = repo_root.join("schemas/chaos-tproxy.openapi.yaml");
    let out_path = repo_root.join("chaos-tproxy-proxy/src/schema/openapi.rs");

    let spec_yaml = std::fs::read_to_string(&spec_path)
        .with_context(|| format!("read {}", spec_path.display()))?;
    let yaml_value: serde_yaml::Value = serde_yaml::from_str(&spec_yaml)?;
    let json = serde_json::to_string(&yaml_value)?;
    let spec: openapiv3::OpenAPI = serde_json::from_str(&json)?;

    let mut generator = progenitor::Generator::default();
    let tokens = generator
        .generate_tokens(&spec)
        .context("progenitor codegen failed")?;
    let file: syn::File = syn::parse2(tokens)?;

    // Find `pub mod types { ... }` and flatten its contents into the
    // top level of the output. Everything else (the empty Client +
    // prelude + `pub use progenitor_client::*`) gets dropped — that
    // way chaos-tproxy-proxy doesn't need progenitor_client / reqwest.
    let types_mod: ItemMod = file
        .items
        .into_iter()
        .find_map(|item| match item {
            Item::Mod(m) if m.ident == "types" => Some(m),
            _ => None,
        })
        .context("no `pub mod types` found in progenitor output")?;
    let inner_items = types_mod
        .content
        .map(|(_, items)| items)
        .unwrap_or_default();

    let flattened = syn::File {
        shebang: None,
        attrs: Vec::new(),
        items: inner_items,
    };
    let content = prettyplease::unparse(&flattened);

    let header = "// @generated by chaos-tproxy-codegen.\n\
                  // Do NOT edit by hand. Re-run\n\
                  //   (cd tools/codegen && cargo run --release)\n\
                  // after editing schemas/chaos-tproxy.openapi.yaml.\n\
                  //\n\
                  // Only the `types` module from progenitor's output is kept;\n\
                  // the (empty) HTTP Client wrapper is intentionally dropped\n\
                  // so chaos-tproxy-proxy doesn't depend on reqwest /\n\
                  // progenitor_client.\n\n\
                  #![allow(clippy::all, missing_docs, unused_imports)]\n\n";

    std::fs::create_dir_all(out_path.parent().unwrap())?;
    std::fs::write(&out_path, format!("{header}{content}"))?;

    println!("wrote {}", out_path.display());
    Ok(())
}
