on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
  build_x86_64:
    name: Upload Release x86-64
    needs: create_release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - target: x86_64-unknown-linux-gnu
          cc: gcc
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          DOCKER_BUILDKIT=1 docker build --build-arg CC=${{ matrix.cc }} --build-arg TARGET=${{ matrix.target }} --build-arg HTTP_PROXY=${HTTP_PROXY} --build-arg HTTPS_PROXY=${HTTPS_PROXY} . -t chaos-mesh/tproxy
          docker run -v ${PWD}:/opt/mount:z --rm --entrypoint cp chaos-mesh/tproxy /tproxy /opt/mount/tproxy
          tar -czvf ./tproxy-${{ matrix.target }}.tar.gz ./tproxy
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }} 
          asset_path: ./tproxy-${{ matrix.target }}.tar.gz
          asset_name: tproxy-${{ matrix.target }}.tar.gz
          asset_content_type: application/zip
  build_aarch64:
    name: Upload Release aarch64
    needs: create_release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            cc: gcc-aarch64-linux-gnu
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu20.04
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          install: |
            apt-get update && apt-get install build-essential ${{ matrix.cc }} curl git pkg-config -y && rm -rf /var/lib/apt/lists/*
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            source $HOME/.cargo/env
            cargo build --release --all
          run: |
            cp /target/release/chaos-tproxy /tproxy
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./tproxy-${{ matrix.target }}.tar.gz
          asset_name: tproxy-${{ matrix.target }}.tar.gz
          asset_content_type: application/zip